// <auto-generated />
using System;
using InvoiceRegisterServer.Code;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceRegisterServer.Migrations
{
    [DbContext(typeof(DbServiceContext))]
    [Migration("20200131113529_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InvoiceRegisterServer.Code.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Client1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client2"
                        });
                });

            modelBuilder.Entity("InvoiceRegisterServer.Code.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Date = new DateTime(2020, 1, 31, 13, 35, 29, 496, DateTimeKind.Local).AddTicks(2772),
                            Description = "description 1",
                            Number = 1,
                            Sum = 100.0
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            Date = new DateTime(2020, 1, 31, 13, 35, 29, 496, DateTimeKind.Local).AddTicks(8579),
                            Description = "description 2",
                            Number = 2,
                            Sum = 200.0
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            Date = new DateTime(2020, 1, 31, 13, 35, 29, 496, DateTimeKind.Local).AddTicks(8604),
                            Description = "description 3",
                            Number = 3,
                            Sum = 300.0
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            Date = new DateTime(2020, 1, 31, 13, 35, 29, 496, DateTimeKind.Local).AddTicks(8606),
                            Description = "description 4",
                            Number = 4,
                            Sum = 400.0
                        });
                });

            modelBuilder.Entity("InvoiceRegisterServer.Code.Invoice", b =>
                {
                    b.HasOne("InvoiceRegisterServer.Code.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
